dvdrentalweb/Models/DVDTitle.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace dvdrentalweb.Models
{
    public class DVDTitle
    {
        [Key]
        public int DVDNumber { get; set; }
        [ForeignKey("CategoryNumber")]
        public int CategoryNumber { get; set; }
        [ForeignKey("StudioNumber")]
        public int StudioNumber { get; set; }
        [ForeignKey("ProducerNumber")]
        public int ProducerNumber { get; set; }
        public string DvdTitle { get; set; }
        public DateTime DateReleased { get; set; }
        public double StandardCharge { get; set; }
        public double PenaltyCharge { get; set; }

        [NotMapped]
        public string ProducerName { get; set; }
        [NotMapped]
        public string StudioName { get; set; }
        [NotMapped]
        public string ActorSurname { get; set; }
        [NotMapped]
        public string ActorFirstName { get; set; }
        [NotMapped]
        public int CopyNumber { get; set; }

    }
}

dvdrentalweb/Controllers/DVDTitleController.cs
using dvdrentalweb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace dvdrentalweb.Controllers
{
    public class DVDTitleController : Controller
    {
        private readonly ShopContext _db;

        public DVDTitleController(ShopContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var objDVDTitleList = _db.DVDTitles.ToList();
            return View(objDVDTitleList);
        }

        // GET
        public IActionResult Create()
        {
            ViewBag.producerName = new SelectList(_db.Producers, "ProducerNumber", "ProducerName");
            ViewBag.categoryName = new SelectList(_db.DVDCategory, "CategoryNumber", "CategoryDescription");
            ViewBag.studioName = new SelectList(_db.Studios, "StudioNumber", "StudioName");
            return View();
        }

        // POST
        [HttpPost]
        public IActionResult Create(DVDTitle obj)
        {
            ModelState.Remove("StudioName");
            ModelState.Remove("ActorFirstName");
            ModelState.Remove("ActorSurName");
            ModelState.Remove("ProducerName");
            if (ModelState.IsValid)
            {
                _db.DVDTitles.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        
        public IActionResult DVDTitleList_02(string SearchText = "")
        {
            var dvdTitleList = (from a in _db.DVDTitles
                               join b in _db.DVDCopys
                               on a.DVDNumber equals b.DVDNumber
                               join c in _db.CastMembers
                               on b.DVDNumber equals c.DVDNumber
                               join d in _db.Actors
                               on c.ActorNumber equals d.ActorNumber
                               join e in _db.Loans
                               on b.CopyNumber equals e.CopyNumber into f
                               from e in f.DefaultIfEmpty()
                               where e.DateReturned != null
                               orderby b.CopyNumber
                               select new DVDTitle
                               {
                                   DvdTitle = a.DvdTitle,
                                   CopyNumber = b.CopyNumber,
                                   ActorFirstName = d.ActorFirstName,
                                   ActorSurname = d.ActorSurName
                               }).ToList();
            var dvdTitleToList = dvdTitleList.ToList();
            if (SearchText != null && SearchText != "")
            {
                dvdTitleToList = dvdTitleList.
                    Where(a => a.ActorSurname.Contains(SearchText)).ToList();
            }
            return View(dvdTitleToList);
            
        }


        public IActionResult DVDTitleList_04()
        {
            try
            {

                var DvDTitleList_01 = (from a in _db.DVDTitles
                                     join b in _db.Producers
                                     on a.ProducerNumber equals b.ProducerNumber
                                     join c in _db.Studios
                                     on a.StudioNumber equals c.StudioNumber
                                     join d in _db.CastMembers
                                     on a.DVDNumber equals d.DVDNumber
                                     join e in _db.Actors
                                     on d.ActorNumber equals e.ActorNumber
                                     orderby a.DateReleased, e.ActorFirstName

                                     select new DVDTitle
                                     {
                                         DVDNumber = a.DVDNumber,
                                         CategoryNumber = a.CategoryNumber,
                                         StudioNumber = a.StudioNumber,
                                         ProducerNumber = a.ProducerNumber,
                                         DvdTitle = a.DvdTitle,
                                         DateReleased = a.DateReleased,
                                         StandardCharge = a.StandardCharge,
                                         PenaltyCharge = a.PenaltyCharge,
                                         ProducerName = b.ProducerName,
                                         StudioName = c.StudioName,
                                         ActorSurname = e.ActorSurName,
                                         ActorFirstName = e.ActorFirstName
                                     });


                var DvDTitleList = DvDTitleList_01.ToList();
                return View(DvDTitleList);
            }
            catch (Exception ex)
            {
                return View();
            }
        }
    }
}

dvdrentalweb/Views/DVDTitle/Create.cshtml
@model DVDTitle

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="Create">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Add Cast Members</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="DvdTitle"></label>
			<input asp-for="DvdTitle" class="form-control"/>
			<span asp-validation-for="DvdTitle" class="text-danger"></span>
		</div>
		<!-- Dropdown-->
		<div class="mb-3">
			<label asp-for="ProducerNumber"></label>
			<!-- <input asp-for="ProducerNumber" class="form-control"/> -->
			@Html.DropDownList("ProducerNumber", ViewBag.producerName as SelectList, "Select Producer", new {@class = "form-control"})
			<span asp-validation-for="ProducerNumber" class="text-danger"></span>
		</div>
		<!-- Dropdown-->
		<div class="mb-3">
			<label asp-for="CategoryNumber"></label>
			@Html.DropDownList("CategoryNumber", ViewBag.categoryName as SelectList, "Select Category", new {@class = "form-control"})
			<span asp-validation-for="CategoryNumber" class="text-danger"></span>
		</div>
		<!-- Dropdown-->
		<div class="mb-3">
			<label asp-for="StudioNumber"></label>
			@Html.DropDownList("StudioNumber", ViewBag.studioName as SelectList, "Select Studio", new {@class = "form-control"})
			<span asp-validation-for="StudioNumber" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="DateReleased"></label>
			<input asp-for="DateReleased" class="form-control"/>
			<span asp-validation-for="DateReleased" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="StandardCharge"></label>
			<input asp-for="StandardCharge" class="form-control"/>
			<span asp-validation-for="StandardCharge" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="PenaltyCharge"></label>
			<input asp-for="PenaltyCharge" class="form-control"/>
			<span asp-validation-for="PenaltyCharge" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Submit</button>
		<a asp-controller="DVDTitle" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

dvdrentalweb/Views/DVDTitle/DVDTitleList_02.cshtml
@model IEnumerable<dvdrentalweb.Models.DVDTitle>

@{
    ViewData["Title"] = "ActorList_01";
}

<h1>View DVDs in the shop from Actor's Name</h1>

<div class="col-4 p-0 0 justify-content-end">
  <form asp-controller="Actor" asp-action="ActorList_02">
      <span class="btn-group">
          <input class="form-control" type="text" name="SearchText" placeholder="Search by Actor surname" />
          <input class="p-1 ml-2 btn-primary " type="submit" value="Search"/>
      </span>
  </form>

  
</div>

<table class="table">

    <thead>
        <tr>
            <th>
               Actor's Name
            </th>
            <th>
               DVD Title
            </th>
            <th>
               Copy Numbers
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.ActorFirstName @item.ActorSurname
            </td>
            <td>
                @item.DvdTitle
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CopyNumber)
            </td>
        </tr>
}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

dvdrentalweb/Views/DVDTitle/DVDTitleList_04.cshtml
@model IEnumerable<dvdrentalweb.Models.DVDTitle>
@{
    ViewData["Title"] = "DVDTitleList_04";
}

<h1>Producer, Studio and Cast Members </h1>

<table class="table">

    <thead>
        <tr>
            <th>
               DVD Title
            </th>
            <th>
               Producer
            </th>
            <th>
               Castlist
            </th>
            <th>
               Studio
            </th>
            <th>
               Date Released
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

@foreach (var item in Model) {
        <tr>
            <td>
                @item.DvdTitle
            </td>
            <td>
                @item.ProducerName
            </td>
            <td>
                @item.ActorFirstName @item.ActorSurname
            </td>
            <td>
                @item.StudioName
            </td>
            <td>
                @item.DateReleased
            </td>
        </tr>
}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

dvdrentalweb/Views/DVDTitle/Index.cshtml
@model IEnumerable<dvdrentalweb.Models.DVDTitle>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h2>DVD Titles</h2>
<a asp-controller="Producer" asp-action="Create" class="btn btn-primary">Add Producer</a>
<a asp-controller="Studio" asp-action="Create" class="btn btn-primary">Add a Studio</a>
<a asp-controller="Actor" asp-action="Create" class="btn btn-primary">Add a Actor</a>
<a asp-controller="DVDTitle" asp-action="Create" class="btn btn-primary">Add a DVD</a>
<a asp-controller="CastMember" asp-action="Create" class="btn btn-primary">Add Cast Member</a>

<table class="table">
    <thead>
        <tr>
            <th>
               DVD Title
            </th>
            <th>
               Date Released
            </th>
            <th>
               Standard Charge
            </th>
            <th>
                Penalty Charge
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.DvdTitle
            </td>
            <td>
                @item.DateReleased
            </td>
            <td>
                @item.StandardCharge
            </td>
            <td>
                @item.PenaltyCharge
            </td>
        </tr>}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>