dvdrentalweb/Models/Loan.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace dvdrentalweb.Models
{
    public class Loan
    {
        [Key]
        public int LoanNumber { get; set; }
        [ForeignKey("LoanTyoeNumber")]
        public int LoanTypeNumber { get; set; }
        [ForeignKey("CopyNumber")]
        public int CopyNumber { get; set; }
        [ForeignKey("MemberNumber")]
        public int MemberNumber { get; set; }
        public DateTime? DateOut { get; set; }
        public DateTime? DateDue { get; set; }
        public DateTime? DateReturned { get; set; }

        [NotMapped]
        public string DVDTitle { get; set; }
        [NotMapped]
        public string MemberLastName { get; set; }
        [NotMapped]
        public string MemberFirstName { get; set; }
        [NotMapped]
        public DateTime MemberDateOfBirth{ get; set; }
        [NotMapped]
        public string MemberAddress { get; set; }
        [NotMapped]
        public string LoanType { get; set; }
        [NotMapped]
        public int LoanDuration { get; set; }
        [NotMapped]
        public int DVDNumber { get; set; }
        [NotMapped]
        public double StandardCharge { get; set; }
        [NotMapped]
        public double PenaltyCharge { get; set; }
        [NotMapped]
        public int AgeRestricted { get; set; }
        [NotMapped]
        public int MembershipCategoryTotalLoans { get; set; }
        [NotMapped]
        public int CategoryNumber { get; set; }
    }
}

dvdrentalweb/Models/LoanType.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace dvdrentalweb.Models
{
    public class LoanType
    {
        [Key]
        public int LoanTypeNumber { get; set; }
        public string Loantype { get; set; }
        public int LoanDuration { get; set; }
        
    }
}

dvdrentalweb/Controllers/LoanController.cs
using dvdrentalweb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;

namespace dvdrentalweb.Controllers
{
    public class LoanController : Controller
    {
        private readonly ShopContext _db;

        public LoanController(ShopContext db)
        {
            _db = db;
        }


        public IActionResult LoanList_05(string SearchText = "")
        {
            try
            {
                var loanList_01 = (from a in _db.Loans
                                   join b in _db.DVDCopys
                                   on a.CopyNumber equals b.CopyNumber
                                   join c in _db.DVDTitles
                                   on b.DVDNumber equals c.DVDNumber
                                   join d in _db.Members
                                   on a.MemberNumber equals d.MemberNumber

                                   select new Loan
                                   {
                                       LoanNumber = a.LoanNumber,
                                       LoanTypeNumber = a.LoanTypeNumber,
                                       CopyNumber = a.CopyNumber,
                                       MemberNumber = a.MemberNumber,
                                       DateOut = a.DateOut,
                                       DateDue = a.DateDue,
                                       DateReturned = a.DateReturned,
                                       DVDTitle = c.DvdTitle,
                                       MemberLastName = d.MemberLastNamae,
                                       MemberFirstName = d.MemberFirstName,
                                   });

                var loanListToList = loanList_01.ToList();
                if (SearchText != null && SearchText != "")
                {
                    loanListToList = loanList_01.
                        Where(a => a.CopyNumber == int.Parse(SearchText)).ToList();
                }
                return View(loanListToList);
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        
        public IActionResult Index()
        {
            var loanList_01 = (from a in _db.Loans
                               join b in _db.LoanTypes
                               on a.LoanTypeNumber equals b.LoanTypeNumber
                               join c in _db.Members
                               on a.MemberNumber equals c.MemberNumber
                               join d in _db.DVDCopys
                               on a.CopyNumber equals d.CopyNumber
                               join e in _db.DVDTitles
                               on d.DVDNumber equals e.DVDNumber
                               join f in _db.DVDCategory
                               on e.CategoryNumber equals f.CategoryNumber
                               join g in _db.MembershipCategories
                               on c.MembershipCategoryNumber equals g.MembershipCategoryNumber

                               select new Loan
                               {
                                   LoanNumber = a.LoanNumber,
                                   LoanTypeNumber = a.LoanTypeNumber,
                                   CopyNumber = a.CopyNumber,
                                   MemberNumber = a.MemberNumber,
                                   MemberFirstName = c.MemberFirstName,
                                   MemberLastName = c.MemberLastNamae,
                                   DateOut = a.DateOut,
                                   DateDue = a.DateDue,
                                   DateReturned = a.DateReturned,
                                   LoanType = b.Loantype,
                                   DVDTitle = e.DvdTitle,
                                   StandardCharge = e.StandardCharge,
                                   PenaltyCharge = e.PenaltyCharge,
                                   AgeRestricted = f.AgeRestricted,
                                   MemberDateOfBirth = c.MemberDateOfBirth,
                                   MembershipCategoryTotalLoans = g.MembershipCategoryTotalLoans
                               }).ToList();
            return View(loanList_01);
        }

        //GET
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var loansFromDb = _db.Loans.Find(id);
           
            if (loansFromDb == null)
            {
                return NotFound();
            }

            return View(loansFromDb);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Loan obj)
        {
            obj.DateReturned = DateTime.Now;
            ModelState.Remove("LoanType");
            ModelState.Remove("DVDTitle");
            ModelState.Remove("MemberAddress");
            ModelState.Remove("MemberLastName");
            ModelState.Remove("MemberFirstName");
            if (ModelState.IsValid)
            {
                _db.Loans.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        //GET
        public IActionResult Create()
        {
            var copyInStock =  from a in _db.DVDTitles
                               join b in _db.DVDCopys
                               on a.DVDNumber equals b.DVDNumber
                               join e in _db.Loans
                               on b.CopyNumber equals e.CopyNumber into f
                               from e in f.DefaultIfEmpty()
                               where e.DateReturned != null
                               orderby b.CopyNumber
                               select new Loan
                               {
                                   DVDTitle = a.DvdTitle,
                                   CopyNumber = b.CopyNumber
                               };

            ViewBag.loanType = new SelectList(_db.LoanTypes, "LoanTypeNumber", "Loantype");
            ViewBag.dvdTitles = new SelectList(copyInStock, "CopyNumber", "DVDTitle");
            ViewBag.memberName = new SelectList(_db.Members, "MemberNumber", "MemberFirstName");
            return View();
        }

        //POST:
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Loan obj)
        {      

            // Check for Age Restriction:
            int memberNumber = obj.MemberNumber;
            int copyNumberForAgeRestricted = obj.CopyNumber;

            // Check for number of loans
            var memberLoanCount = _db.Loans.GroupBy(a => a.MemberNumber).Select(g => new { Key = g.Key, Count = g.Count() });
            
            try
            {
                obj.DateOut = DateTime.Now;
                int daysDue = GetLoanDuration(obj.LoanTypeNumber);
                obj.DateDue = DateTime.Now.AddDays(daysDue);
                int memberAge = GetAge(obj.MemberNumber);
                int ageRestriction = GetAgeRestricted(obj.CopyNumber);
                int totalLoanCount = GetMembersCurrentNumberOfLoans(obj.MemberNumber);
                int allowedLoanCount = GetMemberTotalAllowedLoans(obj.MemberNumber);
                if (memberAge > ageRestriction)
                {
                    if(totalLoanCount <= allowedLoanCount)
                    {
                        ModelState.Remove("DVDTitle");
                        ModelState.Remove("LoanType");
                        ModelState.Remove("MemberAddress");
                        ModelState.Remove("MemberFirstName");
                        ModelState.Remove("MemberLastName");
                        if (ModelState.IsValid)
                        {
                            _db.Loans.Add(obj);
                            _db.SaveChanges();
                            return RedirectToAction("Index");
                        }
                    }
                }
            }
            catch
            {
                return View(obj);
            }
            return View(obj); 
            
            int GetAgeRestricted(int copyNumber)
            {
                int DvdNumber = _db.DVDCopys.Find(copyNumber).DVDNumber;
                int DvdCategoryNumber = _db.DVDTitles.Find(DvdNumber).CategoryNumber;
                var DvdCategory = _db.DVDCategory.Find(DvdCategoryNumber);
                int ageRestricted = DvdCategory.AgeRestricted;
                return ageRestricted;
            }

            int GetAge(int memberNumber)
            {
                var Member = _db.Members.Find(memberNumber);
                var DOB = Member.MemberDateOfBirth;
                int age = DateTime.Now.Year - DOB.Year;
                return age;
            }

            int GetLoanDuration(int? loanTypeNumber)
            {
                int loanDuration = _db.LoanTypes.Find(loanTypeNumber).LoanDuration;                
                return loanDuration;
            }

            int GetMemberTotalAllowedLoans(int memberNumber)
            {
                int MemberCategoryNumber = _db.Members.Find(memberNumber).MembershipCategoryNumber;
                int MembershipCategoryTotalLoans = _db.MembershipCategories.Find(MemberCategoryNumber).MembershipCategoryTotalLoans;
                return MembershipCategoryTotalLoans;
            }

            int GetMembersCurrentNumberOfLoans(int memberNumber)
            {
                var totalLoansNotReturned = (from a in _db.Loans
                                            where a.DateReturned == null
                                            select a).ToList();
                var groups = totalLoansNotReturned.GroupBy(n => n.MemberNumber)
                         .Select(n => new
                         {
                             number = n.Key,

dvdrentalweb/Views/Loan/Create.cshtml
@model Loan

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<form method="post" asp-action="Create">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Issue a DVD on Loan</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="LoanTypeNumber"></label>
			@Html.DropDownList("LoanTypeNumber", new List<SelectListItem>

                 {
                    new SelectListItem{ Text="1-day", Value = "0" },
                    new SelectListItem{ Text="3-day", Value = "1" },
					new SelectListItem{ Text="5-day", Value = "2" }
                 },"Select Loan Type",new {@class = "form-control"})
			<span asp-validation-for="LoanTypeNumber" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="CopyNumber"></label>
			<!-- <input asp-for="CopyNumber" class="form-control"/> -->
			<!-- <span asp-validation-for="CopyNumber" class="text-danger"></span> -->
			@Html.DropDownList("CopyNumber", ViewBag.dvdTitles as SelectList, "Select DVD", new {@class = "form-control"})
		</div>
		<div class="mb-3">
			<label asp-for="MemberNumber"></label>
			<!-- <input asp-for="MemberNumber" class="form-control"/> -->
			<!-- <span asp-validation-for="MemberNumber" class="text-danger"></span> -->
			@Html.DropDownList("MemberNumber", ViewBag.memberName as SelectList, "Select Member First name", new {@class = "form-control"})
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Submit</button>
		<a asp-controller="DVDTitle" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

dvdrentalweb/Views/Loan/Index.cshtml
@model IEnumerable<dvdrentalweb.Models.Loan>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Return The DVD Copy</h1>

<table class="table">

    <thead>
        <tr>
            <th>
               Customer Name
            </th>
            <th>
               DVD Title
            </th>
            <th>
               Copy Number
            </th>
            <th>
               Date Out
            </th>
            <th>
               Date Due
            </th>
            <th>
               Date Returned
            </th>
            <th>
               Standard Charge
            </th>
            <th>
               Penalty Charge
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.MemberFirstName @item.MemberLastName
            </td>
            <td>
                @item.DVDTitle
            </td>
            <td>
                @item.CopyNumber
            </td>
            <td>
                @item.DateOut
            </td>
            <td>
                @item.DateDue
            </td>            
            @if(item.DateReturned == null)
                {
                    <td>
                        Not Returned
                    </td>
                } 
                else
                {
                    <td>
                        @item.DateReturned                            
                    </td>
                    
                }
            <td>
                @item.StandardCharge
            </td>
            <td style="color:red">
                    @if (item.DateDue < item.DateReturned)
                    {
                        @item.PenaltyCharge
                    }
            </td>
            <td>
                @if(item.DateReturned == null)
                {
                     <a asp-controller="Loan" asp-action="Update" asp-route-id="@item.LoanNumber"
                        class="btn btn-primary mx-2">Return</a> 
                }
            </td>
        </tr>}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

dvdrentalweb/Views/Loan/IssueIndex.cshtml
@model IEnumerable<dvdrentalweb.Models.Loan>

<table class="table">
    <thead>
        <tr>
            <th>
               DVD Title
            </th>
            <th>
               Copy Numbers
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.DVDTitle
            </td>
            <td>
                @item.CopyNumber
            </td>
            <td>
                <a asp-controller="Loan" asp-action="Create" class="btn btn-primary">Issue the DVD</a>
            </td>
        </tr>
}
    </tbody>
</table>

dvdrentalweb/Views/Loan/LoanList_05.cshtml
@model IEnumerable<dvdrentalweb.Models.Loan>
@{
    ViewData["Title"] = "LoanList_05";
}

<h1>Loan of Copy</h1>

<div class="col-4 p-0 0 justify-content-end">
  <form asp-controller="Loan" asp-action="LoanList_05">
      <span class="btn-group">
          <input class="form-control" type="text" name="SearchText" placeholder="Search by Copy Number" />
          <input class="p-1 ml-2 btn-primary " type="submit" value="Search"/>
      </span>
  </form>  
</div>

<table class="table">

    <thead>
        <tr>
            <th>
               Copy Numbers
            </th>
            <th>
               DVD Title
            </th>
            <th>
               Date Out
            </th>
            <th>
                Date Returned
            </th>
            <th>
                Date Due
            </th>
            <th>
                Member Name (Last Loan)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.CopyNumber
            </td>
            <td>
                @item.DVDTitle
            </td>
            <td>
                @item.DateOut
            </td>
            @if(item.DateReturned == null)
                {
                    <td>
                        Not Returned
                    </td>
                } 
                else
                {
                    <td>
                        @item.DateReturned                            
                    </td>
                    
                }
            <td>
                @item.DateDue
            </td>
            <td>
                @item.MemberFirstName @item.MemberLastName
            </td>
        </tr>
}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

dvdrentalweb/Views/Loan/LoanList_11.cshtml
@model IEnumerable<dvdrentalweb.Models.Loan>

<table class="table">
    <thead>
        <tr>
            <th>
               DVD Title
            </th>
            <th>
               Copy  No
            </th>
            <th>
               Date Out
            </th>
            <th>
               Member Name
            </th>
            <th>
               Number of Loans for the day
            </th>            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.DVDTitle
            </td>
            <td>
                @item.CopyNumber
            </td>
            <td>
                @item.DateOut
            </td>
            <td>
                @item.MemberFirstName @item.MemberLastName
            </td>
            <td>
                
            </td>
        </tr>
}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

dvdrentalweb/Views/Loan/LoanList_12.cshtml
@model IEnumerable<dvdrentalweb.Models.Loan>

<table class="table">
    <thead>
        <tr>
            <th>
               Member Name
            </th>
            <th>
               Member Address
            </th>
            <th>
               Last Loaned DVD Title
            </th>
            <th>
               Last Date Out
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.MemberFirstName @item.MemberLastName
            </td>
            <td>
                @item.MemberAddress
            </td>
            <td>
                @item.DVDTitle
            </td>
            <td>
                @item.DateOut
            </td>
        </tr>
}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

dvdrentalweb/Views/Loan/LoanList_13.cshtml
@model IEnumerable<dvdrentalweb.Models.Loan>

    <h2>Inactive DVDs</h2>
<table class="table">
    <thead>
        <tr>
            <th>
               DVD Title
            </th>
            <th>
               Last Date Out
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.DVDTitle
            </td>
            <td>
                @item.DateOut
            </td>
        </tr>
}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

dvdrentalweb/Views/Loan/Update.cshtml
@model Loan

<form method="post" asp-action="Update">
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Return DVD</h2>
			<hr />
		</div>
		@*<div asp-validation-summary="All"></div>*@
		<div class="mb-3">
			<label asp-for="LoanTypeNumber"></label>
			<input asp-for="LoanTypeNumber" class="form-control" disabled/>
			<span asp-validation-for="LoanTypeNumber" class="text-danger"></span>
		</div>		
		<div class="mb-3">
			<label asp-for="CopyNumber"></label>
			<input asp-for="CopyNumber" class="form-control" disabled/>
			<span asp-validation-for="CopyNumber" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="MemberNumber"></label>
			<input asp-for="MemberNumber" class="form-control" disabled/>
			<span asp-validation-for="MemberNumber" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="DateOut"></label>
			<input asp-for="DateOut" class="form-control" disabled/>
			<span asp-validation-for="DateOut" class="text-danger"></span>
		</div>
		<div class="mb-3">
			<label asp-for="DateDue"></label>
			<input asp-for="DateDue" class="form-control" disabled/>
			<span asp-validation-for="DateDue" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Return</button>
		<a asp-controller="Loan" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}