dvdrentalweb/Models/DVDCopy.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace dvdrentalweb.Models
{
    public class DVDCopy
    {
        [Key]
        public int CopyNumber { get; set; }
        [ForeignKey("DVDNumber")]
        public int DVDNumber { get; set; }
        public DateTime DatePurchase{ get; set; }
        [NotMapped]
        public string DVDTitle{ get; set; }
        [NotMapped]
        public DateTime? DateReturned { get; set; }
        [NotMapped]
        public DateTime? DateReleased { get; set; }

    }
}

dvdrentalweb/Controllers/DVDCopyController.cs
using dvdrentalweb.Models;
using Microsoft.AspNetCore.Mvc;

namespace dvdrentalweb.Controllers
{
    public class DVDCopyController : Controller
    {
        private readonly ShopContext _db;

        public DVDCopyController(ShopContext db)
        {
            _db = db;
        }

        public IActionResult DVDCopyList_10()
        {
            try
            {

                var DvDCopyList_10 = (from a in _db.DVDCopys
                                      join b in _db.DVDTitles
                                      on a.DVDNumber equals b.DVDNumber
                                      join c in _db.Loans
                                      on a.CopyNumber equals c.CopyNumber
                                      where b.DateReleased <= DateTime.Now.AddDays(-365)
                                      where c.DateReturned != null                    

                                       select new DVDCopy
                                       {
                                           DVDNumber = a.DVDNumber,
                                           CopyNumber = a.CopyNumber,
                                           DatePurchase = a.DatePurchase,
                                           DVDTitle = b.DvdTitle,
                                           DateReleased = b.DateReleased,
                                           DateReturned = c.DateReturned
                                       });


                var DvDCopyList = DvDCopyList_10.ToList();
                return View(DvDCopyList);
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        //GET
        public IActionResult Delete(int? CopyNumber)
        {
            if (CopyNumber == null || CopyNumber == 0)
            {
                return NotFound();
            }
            var DVDCopyFromDb = _db.DVDCopys.Find(CopyNumber);
            if (DVDCopyFromDb == null)
            {
                return NotFound();
            }
            return View(DVDCopyFromDb);
        }

        //POST
        [HttpPost]
        public IActionResult DeletePOST(DVDCopy obj)
        {
            var DVDCopyFromDb = _db.DVDCopys.Find(obj.CopyNumber);
            if (DVDCopyFromDb == null)
            {
                return NotFound();
            }
            
            _db.DVDCopys.Remove(DVDCopyFromDb);
            _db.SaveChanges();
            return RedirectToAction("Index");
            
            
        }


    }
}

dvdrentalweb/Views/DVDCopy/DVDCopyList_10.cshtml
@model IEnumerable<dvdrentalweb.Models.DVDCopy>
@{
    ViewData["Title"] = "Delete DVDs";
}

<h1>Removing Old DVDs</h1>

<table class="table">
    <thead>
        <tr>
            <th>
               DVD Title
            </th>
            <th>
               Copy Number
            </th>
            <th>
               Date Released
            </th>
            <th>
               
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.DVDTitle
            </td>
            <td>
                @item.CopyNumber
            </td>
            <td>
                @item.DateReleased 
            </td>
            <td>
                <div class="w-75 btn-group" role="group">
                        <a asp-controller="DVDCopy" asp-action="Delete" asp-route-CopyNumber="@item.CopyNumber"
                        class="btn btn-danger mx-2"> <i class="bi bi-trash-fill"></i> Delete</a>
				</div>
            </td>
        </tr>
}
    </tbody>
</table>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

dvdrentalweb/Views/DVDCopy/Delete.cshtml
@model DVDCopy

<form method="post" asp-action="Delete">
	<input asp-for="CopyNumber" hidden />
	<div class="border p-3 mt-4">
		<div class="row pb-2">
			<h2 class="text-primary">Delete DVD Copy</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for="CopyNumber"></label>
			<input asp-for="CopyNumber" disabled class="form-control" />
		</div>
		<button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
		<a asp-controller="DVDCopy" asp-action="DVDCopyList_10" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>
	</div>
</form>

@section Scripts{
	@{
		<partial name="_ValidationScriptsPartial" />
	}
}